### ISSUE TITLE
powerdevil initialization error

### ISSUE THREAD

**Issue by HenryHu** [freebsd/freebsd-ports-kde#13]
Now, if you start /usr/local/lib/libexec/org_kde_powerdevil, it says "cannot load meta data from /usr/local/lib/qt5/plugins/kf5/powerdevil/powerdevilupowerbackend.so" followed by "... fail to initialize".
The reason is that the patch in plasma5-powerdevil removes upower/powerdevilupowerbackend.cpp from the source files, which contains the plugin info.
Instead, another patch should be created which just comment out the sections in that file which uses udev.
After making this change, there is no more failed initialization of powerdevil.

**Comment by adriaandegroot** [comment]
This was committed to ports a long time back, a little after  @HenryHu 's branch was merged in. Closing issue.
