### ISSUE TITLE
no libinput :(

### ISSUE THREAD

**Issue by zoujiaqing** [freebsd/freebsd-ports-kde#46]
I upgrade plasma version to 5.16.1

Now there are different errors.
I start dbus service in rc.conf

I check dbus status:
```sh
service dbus status
dbus is running as pid 1029.
```

My shell wayland.sh:
```sh
mkdir /tmp/1000
export XDG_RUNTIME_DIR=/tmp/1000
export $(dbus-launch)
kwin_wayland --drm --libinput --xwayland startkde
```

Error:
```sh
./wayland.sh

QObject::connect(KWin::LibInput::Connection, QObject): invalid null parameter
QObject::connect(KWin::LibInput::Connection, QObject): invalid null parameter
no libinput :(
```

From freebsd forums thread link url:
https://forums.freebsd.org/threads/kglobalaccel-runtime-failed-to-register-service-org-kde-kglobalaccel.71159/

**Comment by adriaandegroot** [comment]
Wayland is still not a mainstream target for us on FreeBSD (it probably deserves more attention, but we're pressed for time just keeping up with "all the rest"). So this works best if you debug it yourself and submit patches, I'm afraid.

As an aside: GH isn't a good place to submit issues; please use https://bugs.freebsd.org/
