### ISSUE TITLE
5.25.2

### ISSUE THREAD

**Issue by rmsickler1** [freebsd/freebsd-ports-kde#95]
When will 5.25.2 reach the ports?

**Comment by adriaandegroot** [comment]
> This is not a good place to file issues or ask questions. Issues should go to FreeBSD's bugzilla, questions can best be asked on the mailing lists or in chat (e.g. #freebsd-desktop on Libera).

Once it's ready. There appear to be (new) PAM-related issues with logging in. Do check the development branches in the KDE fork of the ports tree, e.g. https://github.com/freebsd/freebsd-ports-kde/tree/plasma5-5.25.2 , and test things for yourself.
